# Generated by Django 5.2.8 on 2025-11-19 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('idplat', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nomplat', models.CharField(max_length=100)),
                ('pu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('idtable', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('occupation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('idreserv', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_de_reserv', models.DateTimeField()),
                ('date_reserve', models.DateTimeField()),
                ('nomcli', models.CharField(max_length=100)),
                ('idtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.table')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idcom', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nomcli', models.CharField(max_length=100)),
                ('typecom', models.CharField(choices=[('TABLE', 'TABLE'), ('EMPORTER', 'EMPORTER')], max_length=20)),
                ('datecom', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.IntegerField(default=1)),
                ('idplat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu')),
                ('idtable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.table')),
            ],
        ),
    ]
